spring:
  datasource:
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/housekeeper_test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    clean-disabled: false